"""create_core_schema

Revision ID: 0001_core_schema
Revises:
Create Date: 2026-08-23 10:04:15.697394
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_core_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "telegram_processed_update_ids",
        sa.Column(
            "update_id",
            sa.BigInteger(),
            nullable=False,
            autoincrement=False,
            comment="Telegram webhook update identifier used as the deduplication key.",
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Time the Telegram update was first accepted by Atlas.",
        ),
        sa.PrimaryKeyConstraint("update_id", name=op.f("pk_telegram_processed_update_ids")),
        comment=(
            "Stores only Telegram update IDs and receipt timestamps to prevent duplicate webhook "
            "processing. Does not store message payloads."
        ),
    )
    op.create_table(
        "external_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_user_id", sa.String(length=256), nullable=False),
        sa.Column("provider_chat_id", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_external_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identities")),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name="uq_external_identities_provider_user_id",
            comment=(
                "Ensures one external provider user ID maps to at most one Atlas user within a "
                "provider."
            ),
        ),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            name="uq_external_identities_provider",
            comment="Ensures an Atlas user has at most one external identity for a provider.",
        ),
    )
    op.execute(
        "COMMENT ON CONSTRAINT uq_external_identities_provider_user_id "
        "ON external_identities IS "
        "'Ensures one external provider user ID maps to at most one Atlas user within a provider.'"
    )
    op.execute(
        "COMMENT ON CONSTRAINT uq_external_identities_provider "
        "ON external_identities IS "
        "'Ensures an Atlas user has at most one external identity for a provider.'"
    )
    op.create_index(
        op.f("ix_external_identities_user_id"), "external_identities", ["user_id"], unique=False
    )
    op.create_table(
        "integrations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("account_identifier", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "connected",
                "degraded",
                "reauthorization_required",
                "disconnected",
                name="integration_status",
                native_enum=False,
            ),
            server_default="connected",
            nullable=False,
        ),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.LargeBinary(), nullable=True),
        sa.Column("token_metadata", sa.JSON(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('connected', 'degraded', 'reauthorization_required', 'disconnected')",
            name=op.f("ck_integrations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_integrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            "capability",
            "account_identifier",
            name="uq_integrations_user_provider_capability_account",
        ),
    )
    op.create_index(op.f("ix_integrations_user_id"), "integrations", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("morning_briefing_time", sa.Time(), nullable=True),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column(
            "notifications_on_weekends",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "workflows",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "waiting_for_input",
                "waiting_for_approval",
                "completed",
                "cancelled",
                "failed",
                name="workflow_status",
                native_enum=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN "
            "('active', 'waiting_for_input', 'waiting_for_approval', "
            "'completed', 'cancelled', 'failed')",
            name=op.f("ck_workflows_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_workflows_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_workflows_user_idempotency_key"),
    )
    op.create_index(op.f("ix_workflows_user_id"), "workflows", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflows_user_id"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_integrations_user_id"), table_name="integrations")
    op.drop_table("integrations")
    op.drop_index(op.f("ix_external_identities_user_id"), table_name="external_identities")
    op.drop_table("external_identities")
    op.drop_table("telegram_processed_update_ids")
    op.drop_table("users")
    # ### end Alembic commands ###
